args<-commandArgs(trailingOnly=TRUE);suppressPackageStartupMessages(library(survival));options(digits=17)
fit<-readRDS(args[1]);out<-args[2];dir.create(out,recursive=TRUE,showWarnings=FALSE)
z<-cox.zph(fit,transform="km")
write.csv(z$table,file.path(out,"PH_tests.csv"),row.names=TRUE)
write.csv(data.frame(time=z$time,transformed_time=z$x,z$y,check.names=FALSE),file.path(out,"scaled_Schoenfeld_residuals.csv"),row.names=FALSE)
png(file.path(out,"scaled_Schoenfeld_plots.png"),width=2400,height=3200,res=150)
par(mfrow=c(ceiling(ncol(z$y)/4),4),mar=c(3,3,2,1))
for(j in seq_len(ncol(z$y))) plot(z,var=j,main=colnames(z$y)[j])
dev.off()
saveRDS(z,file.path(out,"PH_object.rds"))
writeLines("Primary predictions were retained before this diagnostic. The primary fit remains unchanged; S4 is mandatory regardless of these tests.",file.path(out,"diagnostic_scope.txt"))
